# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82b9aab88bba1e5d140f46e78c48464c4f701ad58929bce8c3010f741cf8604f25051844c000c0f3b183e14b1a5f406e4ace928ae1abbdfd81f0040c63713eff

test:
  secret_key_base: 4c2557f7d3a2630f9d097a854a96507a4023b53c622a8dcc73060ea56a39d46c9cc6717275a47a9b135917961bd9e08790f327ac9b69d11a456a6be300e0bc48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
